"use client";

// 自动化任务 tab — task list + run reports + templates + create dialog,
// mirroring the reference TasksView (cubepilot web/src/views/TasksView.tsx).
// Runs are simulated server-side: a POST run returns immediately and the
// report flips from "running" to "success" a few seconds later, so the pane
// polls the report list while the newest run is in flight.

import { Box } from "@mui/material";
import { ReactNode, useCallback, useEffect, useRef, useState } from "react";

import { cronDescription, isValidCron } from "@/lib/cubepilot/cron";
import type { Report, Task, TaskTemplate } from "@/lib/cubepilot/types";
import { useI18n } from "@/lib/i18n";

import { downloadText, fmtDuration, fmtTime } from "./format";
import { Markdown } from "./Markdown";
import { Btn, Card, CardHead, CpInput, CpTextArea, Icons, Pill, Spinner, inputSx, monoSx, useToast } from "./ui";

// Interpolate {{param}} placeholders (client preview; the server re-renders
// authoritatively on save).
function renderInstruction(instruction: string, params: Record<string, string>): string {
  let out = instruction;
  for (const [k, v] of Object.entries(params)) {
    out = out.split("{{" + k + "}}").join(v);
  }
  return out;
}

function defaultParams(t: TaskTemplate): Record<string, string> {
  const params: Record<string, string> = {};
  for (const p of t.paramsSchema) {
    if (p.default !== undefined) params[p.name] = p.default;
  }
  return params;
}

const POLL_MS = 3000;

export function TasksPane() {
  const { t } = useI18n();
  const { showToast, toastView } = useToast();

  const [tasks, setTasks] = useState<Task[]>([]);
  const [templates, setTemplates] = useState<TaskTemplate[]>([]);
  const [selectedTaskId, setSelectedTaskId] = useState<string | null>(null);
  const [reports, setReports] = useState<Report[]>([]);
  const [reportIndex, setReportIndex] = useState(0);
  const [running, setRunning] = useState(false);
  const [segTab, setSegTab] = useState<"list" | "templates">("list");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [trigger, setTrigger] = useState<"Cron" | "Manual">("Cron");
  const [form, setForm] = useState({
    name: "",
    prompt: "",
    cron: "0 2 * * *",
    templateRef: "",
    params: {} as Record<string, string>,
  });
  const pollTimer = useRef<ReturnType<typeof setInterval> | null>(null);

  const selectedTask = tasks.find((x) => x.id === selectedTaskId) ?? null;
  const selectedReport = reports[Math.min(reportIndex, reports.length - 1)] ?? null;

  const loadTasks = useCallback(async () => {
    try {
      const res = await fetch("/api/cubepilot/tasks");
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { tasks: Task[] };
      setTasks(body.tasks);
      setSelectedTaskId((prev) => (prev && body.tasks.some((x) => x.id === prev) ? prev : null));
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    }
  }, [showToast, t]);

  const loadTemplates = useCallback(async () => {
    try {
      const res = await fetch("/api/cubepilot/tasktemplates");
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { taskTemplates: TaskTemplate[] };
      setTemplates(body.taskTemplates);
    } catch (e) {
      console.error("loadTemplates", e);
    }
  }, []);

  const loadReports = useCallback(async (id: string) => {
    try {
      const res = await fetch(`/api/cubepilot/tasks/${encodeURIComponent(id)}/reports`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { reports: Report[] };
      setReports(body.reports);
      setReportIndex((prev) => Math.max(0, Math.min(prev, body.reports.length - 1)));
    } catch {
      setReports([]);
    }
  }, []);

  // Poll while the newest report of the selected task is still running.
  const newestRunning = reports.length > 0 && reports[0].status === "running";
  useEffect(() => {
    if (!selectedTaskId || !newestRunning) return;
    pollTimer.current = setInterval(() => void loadReports(selectedTaskId), POLL_MS);
    return () => {
      if (pollTimer.current) clearInterval(pollTimer.current);
    };
  }, [selectedTaskId, newestRunning, loadReports]);

  // Mount-only: loadTasks' identity changes every render (its t dep is
  // regenerated by useI18n), and the fetched data is locale-neutral, so a
  // load-once effect is what we want.
  /* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
  useEffect(() => {
    void loadTasks();
    void loadTemplates();
    return () => {
      if (pollTimer.current) clearInterval(pollTimer.current);
    };
  }, []);
  /* eslint-enable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

  function templateLabel(task: Task): string {
    if (!task.templateRef) return t("cubepilot.tasks.freeForm");
    const tpl = templates.find((x) => x.name === task.templateRef);
    return tpl ? tpl.displayName : task.templateRef;
  }

  function scheduleCell(task: Task): string {
    if (!task.schedule || !task.schedule.trim()) return t("cubepilot.tasks.scheduleManual");
    const desc = cronDescription(task.schedule);
    return (desc.text ?? task.schedule) + " (UTC)";
  }

  async function selectTask(id: string) {
    setSelectedTaskId(id);
    await loadReports(id);
  }

  async function toggleTask(task: Task) {
    try {
      // Send the state we want, not "flip": a retry then cannot undo the first
      // call (the row's own state is the source of truth for the button).
      const res = await fetch(`/api/cubepilot/tasks/${encodeURIComponent(task.id)}/toggle`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ state: task.enabled ? "Paused" : "Enabled" }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      showToast(task.enabled ? t("cubepilot.toggledOff") : t("cubepilot.toggledOn"));
      await loadTasks();
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    }
  }

  async function deleteTask(task: Task) {
    if (!window.confirm(t("cubepilot.deleteConfirm", { name: task.name }))) return;
    try {
      const res = await fetch(`/api/cubepilot/tasks/${encodeURIComponent(task.id)}`, { method: "DELETE" });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      showToast(t("cubepilot.deleted"));
      setSelectedTaskId(null);
      setReports([]);
      await loadTasks();
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    }
  }

  async function runTaskId(id: string) {
    if (running) return;
    setRunning(true);
    try {
      const res = await fetch(`/api/cubepilot/tasks/${encodeURIComponent(id)}/run`, { method: "POST" });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { started: boolean };
      if (body.started) showToast(t("cubepilot.runStarted"));
      // Refresh the selected task's report list so the new "running" report
      // appears and the poll effect picks it up.
      if (id === selectedTaskId) await loadReports(id);
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    } finally {
      setRunning(false);
    }
  }

  function runSelected() {
    if (!selectedTaskId) {
      showToast(t("cubepilot.selectTaskFirst"));
      return;
    }
    void runTaskId(selectedTaskId);
  }

  function resetForm() {
    setForm({ name: "", prompt: "", cron: "0 2 * * *", templateRef: "", params: {} });
  }

  function openDialog(templateName?: string) {
    resetForm();
    setTrigger("Cron");
    setDialogOpen(true);
    if (templateName) onChangeTemplate(templateName);
  }

  function onChangeTemplate(templateName: string) {
    if (!templateName) {
      setForm((f) => ({ ...f, templateRef: "", params: {} }));
      return;
    }
    const tpl = templates.find((x) => x.name === templateName);
    if (!tpl) return;
    setForm((f) => ({
      ...f,
      templateRef: templateName,
      params: defaultParams(tpl),
      cron: tpl.defaultCron || f.cron || "0 2 * * *",
    }));
  }

  function setParam(name: string, value: string) {
    setForm((f) => ({ ...f, params: { ...f.params, [name]: value } }));
  }

  async function createTask() {
    const name = form.name.trim();
    if (!name) {
      showToast(t("cubepilot.err.nameRequired"));
      return;
    }
    const activeTemplate = templates.find((x) => x.name === form.templateRef);
    if (!activeTemplate && !form.prompt.trim()) {
      showToast(t("cubepilot.err.promptRequired"));
      return;
    }
    if (trigger === "Cron") {
      if (!form.cron.trim()) {
        showToast(t("cubepilot.err.scheduleRequired"));
        return;
      }
      if (!isValidCron(form.cron)) {
        showToast(cronDescription(form.cron).error ?? "cron");
        return;
      }
    }
    const schedule = trigger === "Cron" ? form.cron.trim() : "";
    try {
      const payload = activeTemplate
        ? { name, schedule, templateRef: activeTemplate.name, params: form.params }
        : { name, prompt: form.prompt.trim(), schedule };
      const res = await fetch("/api/cubepilot/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { task: Task };
      setDialogOpen(false);
      resetForm();
      showToast(t("cubepilot.created", { name }));
      await loadTasks();
      await selectTask(body.task.id);
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    }
  }

  function exportReport() {
    const r = selectedReport;
    if (!r) {
      showToast(t("cubepilot.exportEmpty"));
      return;
    }
    downloadText(
      `report-${r.id}.md`,
      `# ${r.taskName}\n\nTime: ${fmtTime(r.startedAt)}\nStatus: ${r.status}\n\n${r.content || ""}`,
    );
  }

  const activeTemplate = templates.find((x) => x.name === form.templateRef);
  const previewPrompt = activeTemplate
    ? renderInstruction(activeTemplate.instruction, form.params)
    : form.prompt;
  const dialogCron = trigger === "Cron" ? cronDescription(form.cron) : null;

  return (
    <Box data-od-id="cp-tasks-pane">
      {/* head */}
      <Box sx={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "16px", mb: "16px", flexWrap: "wrap" }}>
        <Box>
          <Box sx={{ fontSize: 18, fontWeight: 650, letterSpacing: "-0.01em" }}>{t("cubepilot.tasks.title")}</Box>
          <Box sx={{ fontSize: 13, color: "text.secondary", mt: "3px" }}>{t("cubepilot.tasks.desc")}</Box>
        </Box>
        <Btn variant="primary" onClick={() => openDialog()} data-od-id="cp-tasks-new">
          {Icons.plus()}
          {t("cubepilot.tasks.new")}
        </Btn>
      </Box>

      {/* segment */}
      <Box
        sx={{
          display: "inline-flex",
          border: 1,
          borderColor: "divider",
          borderRadius: "var(--radius)",
          overflow: "hidden",
          mb: "14px",
          bgcolor: "background.default",
        }}
      >
        {(["list", "templates"] as const).map((tab) => (
          <Box
            key={tab}
            component="button"
            type="button"
            onClick={() => setSegTab(tab)}
            data-od-id={`cp-tasks-seg-${tab}`}
            sx={{
              px: "14px",
              py: "7px",
              fontSize: 13,
              fontWeight: segTab === tab ? 600 : 400,
              border: "none",
              cursor: "pointer",
              display: "inline-flex",
              alignItems: "center",
              gap: "7px",
              bgcolor: segTab === tab ? "var(--accent-soft)" : "transparent",
              color: segTab === tab ? "var(--accent-strong)" : "text.secondary",
              "&:hover": { color: "text.primary" },
            }}
          >
            {tab === "list" ? t("cubepilot.tasks.seg.list") : t("cubepilot.tasks.seg.templates")}
            {tab === "templates" ? (
              <Box component="span" sx={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "text.secondary" }}>
                {templates.length}
              </Box>
            ) : null}
          </Box>
        ))}
      </Box>

      {segTab === "list" ? (
        <>
          <Card sx={{ mb: "16px" }}>
            <CardHead
              title={t("cubepilot.tasks.listTitle")}
              hint={t("cubepilot.tasks.listHint", { count: tasks.length })}
              actions={
                <Btn small disabled={running || !selectedTaskId} onClick={runSelected} data-od-id="cp-tasks-run-now">
                  {running ? <Spinner size={11} color="#fff" /> : Icons.run({ size: 12 })}
                  {running ? t("cubepilot.tasks.running") : t("cubepilot.tasks.runNow")}
                </Btn>
              }
            />
            <Box sx={{ overflowX: "auto" }}>
              <Box component="table" sx={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <Box component="thead">
                  <Box component="tr">
                    {["", t("cubepilot.tasks.col.name"), t("cubepilot.tasks.col.template"), t("cubepilot.tasks.col.trigger"), t("cubepilot.tasks.col.schedule"), t("cubepilot.tasks.col.status"), t("cubepilot.tasks.col.last"), t("cubepilot.tasks.col.next"), t("cubepilot.tasks.col.creator"), ""].map(
                      (h, i) => (
                        <Box
                          key={i}
                          component="th"
                          sx={{ textAlign: "left", px: "12px", py: "9px", borderBottom: 1, borderColor: "divider", color: "text.secondary", fontSize: 11.5, fontWeight: 600, whiteSpace: "nowrap" }}
                        >
                          {h}
                        </Box>
                      ),
                    )}
                  </Box>
                </Box>
                <Box component="tbody">
                  {tasks.length === 0 ? (
                    <Box component="tr">
                      <Box component="td" colSpan={10} sx={{ textAlign: "center", color: "text.secondary", p: "24px" }}>
                        {t("cubepilot.tasks.empty")}
                      </Box>
                    </Box>
                  ) : null}
                  {tasks.map((task) => (
                    <Box
                      key={task.id}
                      component="tr"
                      onClick={() => void selectTask(task.id)}
                      data-od-id={`cp-task-row-${task.id}`}
                      sx={{
                        cursor: "pointer",
                        bgcolor: selectedTaskId === task.id ? "var(--accent-soft)" : "transparent",
                        "&:hover": { bgcolor: selectedTaskId === task.id ? "var(--accent-soft)" : "color-mix(in oklch, var(--fg) 3%, transparent)" },
                      }}
                    >
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider" }}>
                        <Box
                          component="span"
                          sx={{
                            display: "inline-block",
                            width: 14,
                            height: 14,
                            borderRadius: "50%",
                            border: `2px solid ${selectedTaskId === task.id ? "var(--accent)" : "var(--border)"}`,
                            bgcolor: selectedTaskId === task.id ? "var(--accent)" : "transparent",
                            boxSizing: "border-box",
                          }}
                        />
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", fontWeight: 600 }}>
                        {task.name}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", whiteSpace: "nowrap" }}>
                        {templateLabel(task)}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", whiteSpace: "nowrap", fontSize: 12.5, color: "text.secondary" }}>
                        {task.schedule ? t("cubepilot.tasks.triggerSched") : t("cubepilot.tasks.triggerManual")}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", ...monoSx, fontSize: 12, whiteSpace: "nowrap" }}>
                        {scheduleCell(task)}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider" }}>
                        <Pill variant={task.enabled ? "ok" : "neutral"} dot>
                          {task.enabled ? t("cubepilot.tasks.enabled") : t("cubepilot.tasks.disabled")}
                        </Pill>
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", ...monoSx, fontSize: 12, whiteSpace: "nowrap" }}>
                        {task.lastRunAt ? fmtTime(task.lastRunAt) : "-"}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", ...monoSx, fontSize: 12, whiteSpace: "nowrap" }}>
                        {task.nextRunAt ? fmtTime(task.nextRunAt) : "-"}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", fontSize: 12.5, color: "text.secondary" }}>
                        {task.creator || "-"}
                      </Box>
                      <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", whiteSpace: "nowrap" }}>
                        <Box sx={{ display: "inline-flex", gap: "4px" }} onClick={(e) => e.stopPropagation()}>
                          <Btn small variant="ghost" onClick={() => void runTaskId(task.id)}>
                            {t("cubepilot.tasks.act.run")}
                          </Btn>
                          <Btn small variant="ghost" onClick={() => void toggleTask(task)}>
                            {task.enabled ? t("cubepilot.tasks.act.disable") : t("cubepilot.tasks.act.enable")}
                          </Btn>
                          <Btn small variant="ghost" onClick={() => void deleteTask(task)}>
                            {t("cubepilot.tasks.act.delete")}
                          </Btn>
                        </Box>
                      </Box>
                    </Box>
                  ))}
                </Box>
              </Box>
            </Box>
          </Card>

          {selectedTask ? (
            <>
              <Box sx={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "12px", mb: "12px", flexWrap: "wrap" }}>
                <Box>
                  <Box sx={{ fontSize: 15, fontWeight: 650 }}>{t("cubepilot.tasks.report.title")}</Box>
                  <Box sx={{ fontSize: 13, color: "text.secondary", mt: "3px" }}>
                    {selectedReport
                      ? t("cubepilot.tasks.report.descSelected", { name: selectedReport.taskName, trigger: selectedReport.trigger === "Cron" ? t("cubepilot.tasks.stat.triggerCron") : t("cubepilot.tasks.stat.triggerManual") })
                      : t("cubepilot.tasks.report.descNone")}
                  </Box>
                </Box>
                <Box sx={{ display: "flex", gap: "8px", alignItems: "center" }}>
                  <Box
                    component="select"
                    value={reports.length ? String(Math.min(reportIndex, reports.length - 1)) : ""}
                    onChange={(e) => setReportIndex(Number(e.target.value) || 0)}
                    aria-label={t("cubepilot.tasks.report.select")}
                    sx={{ ...inputSx, width: "auto", py: "5px", fontSize: 12.5 }}
                    data-od-id="cp-tasks-report-select"
                  >
                    {reports.map((r, i) => (
                      <Box key={r.id} component="option" value={i}>
                        {fmtTime(r.startedAt)} · {r.trigger === "Cron" ? t("cubepilot.tasks.stat.triggerCron") : t("cubepilot.tasks.stat.triggerManual")}
                        {r.status === "failed" ? ` - ${t("cubepilot.tasks.status.failed")}` : r.status === "running" ? ` - ${t("cubepilot.tasks.status.running")}` : ""}
                      </Box>
                    ))}
                  </Box>
                  <Btn onClick={exportReport} data-od-id="cp-tasks-export">
                    {Icons.export({ size: 13 })}
                    {t("cubepilot.tasks.report.export")}
                  </Btn>
                </Box>
              </Box>

              {selectedReport ? (
                <Box data-od-id="cp-tasks-report">
                  <Box sx={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "14px", mb: "16px" }}>
                    <StatBox
                      label={t("cubepilot.tasks.stat.lastRun")}
                      value={<Box component="span" sx={{ fontSize: 18 }}>{fmtTime(selectedReport.startedAt)}</Box>}
                      sub={
                        selectedReport.status === "running"
                          ? t("cubepilot.tasks.stat.inProgress")
                          : t("cubepilot.tasks.stat.duration", { duration: fmtDuration(selectedReport.startedAt, selectedReport.finishedAt || new Date().toISOString()) })
                      }
                    />
                    <StatBox
                      label={t("cubepilot.tasks.stat.runs")}
                      value={reports.length}
                      sub={t("cubepilot.tasks.stat.runsSub")}
                    />
                    <StatBox
                      label={t("cubepilot.tasks.stat.status")}
                      value={
                        <Box
                          component="span"
                          sx={{
                            fontSize: 18,
                            display: "inline-flex",
                            alignItems: "center",
                            gap: "8px",
                            color:
                              selectedReport.status === "failed"
                                ? "#e15c5c"
                                : selectedReport.status === "running"
                                  ? "var(--accent)"
                                  : "#27c37b",
                          }}
                        >
                          {selectedReport.status === "running" ? <Spinner /> : null}
                          {selectedReport.status === "success"
                            ? t("cubepilot.tasks.status.success")
                            : selectedReport.status === "failed"
                              ? t("cubepilot.tasks.status.failed")
                              : t("cubepilot.tasks.status.running")}
                        </Box>
                      }
                      sub={
                        selectedReport.trigger === "Cron"
                          ? t("cubepilot.tasks.stat.triggerCron")
                          : t("cubepilot.tasks.stat.triggerManual")
                      }
                    />
                  </Box>

                  <Card>
                    <CardHead
                      title={t("cubepilot.tasks.report.content")}
                      hint={`${fmtTime(selectedReport.startedAt)} · ${selectedReport.status === "success" ? t("cubepilot.tasks.status.success") : selectedReport.status === "failed" ? t("cubepilot.tasks.status.failed") : t("cubepilot.tasks.status.running")}`}
                    />
                    <Box sx={{ p: "16px 18px 18px" }}>
                      {selectedReport.content ? (
                        <Markdown text={selectedReport.content} />
                      ) : selectedReport.status === "running" ? (
                        <Box sx={{ display: "flex", alignItems: "center", gap: "8px", color: "text.secondary", fontSize: 13 }}>
                          <Spinner />
                          {t("cubepilot.tasks.report.running")}
                        </Box>
                      ) : (
                        <Box sx={{ color: "text.secondary", fontSize: 13 }}>{t("cubepilot.tasks.report.empty")}</Box>
                      )}
                    </Box>
                  </Card>
                </Box>
              ) : null}
            </>
          ) : null}
        </>
      ) : (
        <Card data-od-id="cp-tasks-templates">
          <CardHead title={t("cubepilot.tasks.templates.title")} hint={t("cubepilot.tasks.templates.hint")} />
          <Box sx={{ overflowX: "auto" }}>
            <Box component="table" sx={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
              <Box component="thead">
                <Box component="tr">
                  {[t("cubepilot.tasks.templates.col.name"), t("cubepilot.tasks.templates.col.desc"), t("cubepilot.tasks.templates.col.cron"), t("cubepilot.tasks.templates.col.ops")].map((h, i) => (
                    <Box key={i} component="th" sx={{ textAlign: "left", px: "12px", py: "9px", borderBottom: 1, borderColor: "divider", color: "text.secondary", fontSize: 11.5, fontWeight: 600 }}>
                      {h}
                    </Box>
                  ))}
                </Box>
              </Box>
              <Box component="tbody">
                {templates.length === 0 ? (
                  <Box component="tr">
                    <Box component="td" colSpan={4} sx={{ textAlign: "center", color: "text.secondary", p: "24px" }}>
                      {t("cubepilot.tasks.templates.empty")}
                    </Box>
                  </Box>
                ) : null}
                {templates.map((tpl) => (
                  <Box key={tpl.name} component="tr">
                    <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider" }}>
                      <Box sx={{ display: "inline-flex", alignItems: "center", gap: "7px" }}>
                        <Pill variant="neutral">
                          {Icons.lock({ size: 11 })}
                          {tpl.displayName}
                        </Pill>
                      </Box>
                    </Box>
                    <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", fontSize: 12.5, color: "text.secondary" }}>
                      {tpl.description}
                    </Box>
                    <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider", ...monoSx, fontSize: 12 }}>
                      {tpl.defaultCron || "-"}
                    </Box>
                    <Box component="td" sx={{ px: "12px", py: "10px", borderBottom: 1, borderColor: "divider" }}>
                      <Btn small variant="ghost" onClick={() => openDialog(tpl.name)}>
                        {t("cubepilot.tasks.templates.create")}
                      </Btn>
                    </Box>
                  </Box>
                ))}
              </Box>
            </Box>
          </Box>
        </Card>
      )}

      {dialogOpen ? (
        <Box
          sx={{
            position: "fixed",
            inset: 0,
            zIndex: 1300,
            bgcolor: "rgba(0,0,0,.45)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            p: "20px",
          }}
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setDialogOpen(false);
          }}
        >
          <Box
            role="dialog"
            aria-modal="true"
            data-od-id="cp-tasks-dialog"
            sx={{
              width: "100%",
              maxWidth: 560,
              maxHeight: "90vh",
              overflowY: "auto",
              bgcolor: "background.default",
              border: 1,
              borderColor: "divider",
              borderRadius: "10px",
              boxShadow: "0 24px 48px rgba(0,0,0,.25)",
            }}
          >
            <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", p: "14px 18px", borderBottom: 1, borderColor: "divider" }}>
              <Box sx={{ fontSize: 15, fontWeight: 650 }}>{t("cubepilot.dialog.title")}</Box>
              <Box component="button" type="button" aria-label="Close" onClick={() => setDialogOpen(false)} sx={{ border: "none", background: "none", cursor: "pointer", color: "text.secondary", display: "flex", p: 2 }}>
                {Icons.close({ size: 16 })}
              </Box>
            </Box>
            <Box sx={{ p: "18px", display: "flex", flexDirection: "column", gap: "14px" }}>
              <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.dialog.name")}</Box>
                <CpInput
                  placeholder={t("cubepilot.dialog.namePh")}
                  aria-label={t("cubepilot.dialog.name")}
                  value={form.name}
                  onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                  data-od-id="cp-tasks-dialog-name"
                />
              </Box>
              <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.dialog.template")}</Box>
                <Box
                  component="select"
                  aria-label={t("cubepilot.dialog.template")}
                  value={form.templateRef}
                  onChange={(e) => onChangeTemplate(e.target.value)}
                  sx={inputSx}
                >
                  <Box component="option" value="">
                    {t("cubepilot.dialog.freeForm")}
                  </Box>
                  {templates.map((tpl) => (
                    <Box key={tpl.name} component="option" value={tpl.name}>
                      {tpl.displayName}
                    </Box>
                  ))}
                </Box>
              </Box>
              {!activeTemplate ? (
                <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                  <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.dialog.prompt")}</Box>
                  <CpTextArea
                    rows={4}
                    placeholder={t("cubepilot.dialog.promptPh")}
                    aria-label={t("cubepilot.dialog.prompt")}
                    value={form.prompt}
                    onChange={(e) => setForm((f) => ({ ...f, prompt: e.target.value }))}
                  />
                </Box>
              ) : (
                <>
                  <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                    <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>
                      {t("cubepilot.dialog.params", { name: activeTemplate.displayName })}
                    </Box>
                    {activeTemplate.paramsSchema.length === 0 ? (
                      <Box sx={{ fontSize: 12.5, color: "text.secondary" }}>{t("cubepilot.dialog.noParams")}</Box>
                    ) : (
                      activeTemplate.paramsSchema.map((p) => (
                        <Box key={p.name} sx={{ display: "flex", flexDirection: "column", gap: "4px" }}>
                          <Box component="label" sx={{ fontSize: 12, color: "text.secondary", textTransform: "capitalize" }}>{p.name}</Box>
                          {p.enum && p.enum.length ? (
                            <Box component="select" aria-label={p.name} value={form.params[p.name] ?? p.default ?? ""} onChange={(e) => setParam(p.name, e.target.value)} sx={inputSx}>
                              {p.enum.map((opt) => (
                                <Box key={opt} component="option" value={opt}>{opt}</Box>
                              ))}
                            </Box>
                          ) : (
                            <CpInput aria-label={p.name} value={form.params[p.name] ?? p.default ?? ""} onChange={(e) => setParam(p.name, e.target.value)} />
                          )}
                        </Box>
                      ))
                    )}
                  </Box>
                  <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                    <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.dialog.preview")}</Box>
                    <Box sx={{ ...monoSx, fontSize: 12, lineHeight: 1.6, whiteSpace: "pre-wrap", maxHeight: 160, overflowY: "auto", border: 1, borderColor: "divider", borderRadius: "6px", p: "10px", bgcolor: "var(--surface)" }}>
                      {previewPrompt || t("cubepilot.dialog.emptyInstruction")}
                    </Box>
                  </Box>
                </>
              )}
              <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.dialog.trigger")}</Box>
                <Box role="radiogroup" aria-label={t("cubepilot.dialog.trigger")} sx={{ display: "flex", gap: "8px" }}>
                  {(["Cron", "Manual"] as const).map((tr) => (
                    <Box
                      key={tr}
                      component="button"
                      type="button"
                      role="radio"
                      aria-checked={trigger === tr}
                      onClick={() => setTrigger(tr)}
                      sx={{
                        px: "12px",
                        py: "7px",
                        fontSize: 13,
                        border: 1,
                        borderRadius: "6px",
                        cursor: "pointer",
                        bgcolor: trigger === tr ? "var(--accent-soft)" : "transparent",
                        color: trigger === tr ? "var(--accent-strong)" : "text.secondary",
                        borderColor: trigger === tr ? "var(--accent)" : "divider",
                        fontWeight: trigger === tr ? 600 : 400,
                      }}
                    >
                      {tr === "Cron" ? t("cubepilot.dialog.triggerCron") : t("cubepilot.dialog.triggerManual")}
                    </Box>
                  ))}
                </Box>
              </Box>
              {trigger === "Cron" && dialogCron ? (
                <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                  <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.dialog.schedule")}</Box>
                  <CpInput aria-label={t("cubepilot.dialog.schedule")} value={form.cron} onChange={(e) => setForm((f) => ({ ...f, cron: e.target.value }))} sx={{ ...monoSx }} data-od-id="cp-tasks-dialog-cron" />
                  {dialogCron.error ? (
                    <Box sx={{ fontSize: 12, color: "#e15c5c" }}>{dialogCron.error}</Box>
                  ) : dialogCron.text ? (
                    <Box sx={{ fontSize: 12, color: "#27c37b" }}>{t("cubepilot.dialog.runsAt", { text: dialogCron.text })}</Box>
                  ) : (
                    <Box sx={{ fontSize: 12, color: "text.secondary" }}>{t("cubepilot.dialog.noSchedule")}</Box>
                  )}
                  {activeTemplate?.defaultCron && dialogCron.text ? (
                    <Box sx={{ fontSize: 11, color: "text.secondary" }}>{t("cubepilot.dialog.templateDefault", { cron: activeTemplate.defaultCron })}</Box>
                  ) : null}
                </Box>
              ) : null}
              <Box sx={{ display: "flex", gap: "9px", alignItems: "flex-start", p: "10px 12px", border: 1, borderColor: "color-mix(in oklch, #e0a13a 40%, var(--border))", borderRadius: "6px", bgcolor: "color-mix(in oklch, #e0a13a 8%, transparent)", fontSize: 12.5, lineHeight: 1.6 }}>
                <Box sx={{ flex: "none", color: "#e0a13a", display: "flex", mt: "1px" }}>{Icons.warn({ size: 14 })}</Box>
                <Box>{t("cubepilot.dialog.notice")}</Box>
              </Box>
            </Box>
            <Box sx={{ display: "flex", justifyContent: "flex-end", gap: "8px", p: "14px 18px", borderTop: 1, borderColor: "divider" }}>
              <Btn onClick={() => setDialogOpen(false)}>{t("cubepilot.dialog.cancel")}</Btn>
              <Btn variant="primary" onClick={() => void createTask()} data-od-id="cp-tasks-dialog-create">
                {t("cubepilot.dialog.create")}
              </Btn>
            </Box>
          </Box>
        </Box>
      ) : null}
      {toastView}
    </Box>
  );
}

function StatBox({ label, value, sub, badge }: { label: string; value: ReactNode; sub?: string; badge?: ReactNode }) {
  return (
    <Box
      sx={{
        bgcolor: "var(--surface)",
        border: 1,
        borderColor: "divider",
        borderRadius: "8px",
        p: "14px 16px",
        display: "flex",
        flexDirection: "column",
        gap: "6px",
      }}
    >
      <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Box sx={{ fontSize: 12, color: "text.secondary", fontWeight: 500 }}>{label}</Box>
        {badge}
      </Box>
      <Box sx={{ fontSize: 26, fontWeight: 650, letterSpacing: "-0.02em", lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>{value}</Box>
      {sub ? <Box sx={{ fontSize: 11.5, color: "text.secondary" }}>{sub}</Box> : null}
    </Box>
  );
}

